### ISSUE TITLE
NASA's Third Rock Radio Stream is Outdated

### ISSUE THREAD

**Issue by mikepierce** [mikepierce/internet-radio-streams#5]
Commit 3d706e32876308433e0fc9707394236407c7b487

I've messaged them, but have a vague memory of messaging them before and not getting a response :c

**Comment by jeffhoughten** [comment]
http://rfcm.streamguys1.com/thirdrock-icy seems to work in VLC.

**Comment by mikepierce** [comment]
It's been updated. Thank you!

https://github.com/mikepierce/internet-radio-streams/commit/fdc45097d8271b695573cb142e6799a9ea12e5e8
